apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: "sriov-network"
  namespace: nvidia-network-operator
spec:
  vlan: 1
  networkNamespace: "default"
  resourceName: "sriov_resource"
  ipam: |
    {
      "datastore": "kubernetes",
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/nv-ipam.d/nv-ipam.kubeconfig"
      },
      "log_file": "/tmp/nv-ipam.log",
      "log_level": "debug",
      "type": "nv-ipam",
      "poolName": "sriov-network"
    }
