apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-1
  namespace: nvidia-network-operator
spec:
  deviceType: netdevice
  mtu: 1500
  nicSelector:
    vendor: "15b3"
  numVfs: 8
  priority: 90
  isRdma: true
  resourceName: sriov_resource
  nodeSelector:
    node-role.kubernetes.io/worker: ""
