FROM nvcr.io/nvidia/mellanox/doca-driver:25.01-0.6.0.0-0-ubuntu24.04-amd64

# Install build tools  
RUN apt-get update && apt-get install -y build-essential git  librdmacm-dev libibverbs-dev

# Clone librdmacm and compile rping  
RUN git clone https://github.com/ofiwg/librdmacm.git && \  
    cd librdmacm/examples && \  
    make rping  

# Copy the compiled binary  
RUN cp librdmacm/examples/rping /usr/local/bin/  

ENTRYPOINT ["rping"]
