#!/bin/bash
#
# pod.yaml configuration file for such a deployment:
#
source ${NETOP_ROOT_DIR}/global_ops.cfg
function usage()
{
  echo "usage:$0 {podname} {num_of_pods} {app namespace}"
  echo "usage:$0 {podname} {num_of_pods} {app namespace} {worker node}"
  exit 1
}
function set_gpus
{
if [ "${NUM_GPUS}" != "" ] && [ "${NUM_GPUS}" -gt 0 ];then
cat << HEREDOC0
        nvidia.com/gpu: '${NUM_GPUS}'
HEREDOC0
fi
}
function get_networks()
{
for NETOP_SU in ${NETOP_SULIST[@]};do
  for DEVDEF in ${NETOP_NETLIST[@]};do
    NIDX=`echo ${DEVDEF}|cut -d',' -f1`
    NETWORKS=${NETWORKS},${NETOP_NETWORK_NAME}-${NETOP_APP_NAMESPACE}-${NIDX}-${NETOP_SU}
  done
done
# trim leading ,
NETWORKS=`echo "${NETWORKS}" | sed 's/,//'`
}
function set_network_resource()
{
for DEVDEF in ${NETOP_NETLIST[@]};do
  NIDX=`echo ${DEVDEF}|cut -d',' -f1`
cat << HEREDOC2
        ${NETOP_RESOURCE_PATH}/${NETOP_RESOURCE}_${NIDX}: '1'
HEREDOC2
done
}
#
# DRA helpers (USECASE=sriovnet_dra): pods consume VFs via ResourceClaim instead
# of the SR-IOV device plugin. ResourceClaimTemplates are generated by
# ops/mk-dra-cr.sh into ${NETOP_NAMESPACE}; pods reference them by name and must
# live in the same namespace (ResourceClaimTemplate is namespaced).
#
function set_container_claims()
{
# Emit container-level `resources.claims:` block referencing pod-level claim names.
echo "      claims:"
for NETOP_SU in ${NETOP_SULIST[@]};do
  for DEVDEF in ${NETOP_NETLIST[@]};do
    NIDX=`echo ${DEVDEF}|cut -d',' -f1`
    echo "      - name: ${NIDX}-${NETOP_SU}"
  done
done
}
function set_pod_resource_claims()
{
# Emit pod-level `resourceClaims:` block linking each local name to the
# ResourceClaimTemplate that mk-dra-cr.sh created.
echo "  resourceClaims:"
for NETOP_SU in ${NETOP_SULIST[@]};do
  for DEVDEF in ${NETOP_NETLIST[@]};do
    NIDX=`echo ${DEVDEF}|cut -d',' -f1`
    cat <<DRA_POD_CLAIM
  - name: ${NIDX}-${NETOP_SU}
    resourceClaimTemplateName: ${NETOP_NETWORK_NAME}-${NIDX}-${NETOP_SU}-claim
DRA_POD_CLAIM
  done
done
}
NAME=${1}
shift
NUM_OF_PODS=${1}
shift
NETOP_APP_NAMESPACE=${1:-'default'}
shift
NODE=${1}
shift
if [ "${NAME}" = "" ];then
  usage
fi
if [ "${NUM_OF_PODS}" = "" ];then
  NUM_OF_PODS=1
fi
mkdir -p apps
cd apps
case ${USECASE} in
sriovnet_dra)
  # ResourceClaimTemplate lives in ${NETOP_NAMESPACE}; the pod must reference
  # it from the same namespace (ResourceClaimTemplate is namespaced).
  if [ "${NETOP_APP_NAMESPACE}" != "${NETOP_NAMESPACE}" ]; then
    echo "WARNING: USECASE=sriovnet_dra: pod namespace '${NETOP_APP_NAMESPACE}' differs from" >&2
    echo "         the ResourceClaimTemplate namespace '${NETOP_NAMESPACE}'." >&2
    echo "         Either run with NETOP_APP_NAMESPACE=${NETOP_NAMESPACE}, or copy each" >&2
    echo "         ResourceClaimTemplate from ${NETOP_NAMESPACE} into ${NETOP_APP_NAMESPACE}." >&2
  fi
  # DRA pods still attach to the SriovNetwork CR via the multus annotation;
  # the DRA driver hands the VF to the pod and the NAD wires up IPAM/CNI.
  get_networks
  ;;
*)
  get_networks
  ;;
esac
rm -f ./${NAME}.yaml
for i in $(seq 1 ${NUM_OF_PODS});do
cat << HEREDOC1 >> ./${NAME}.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: ${NAME}-${i}
HEREDOC1
cat << ANNOTATIONS >> ./${NAME}.yaml
  annotations:
    k8s.v1.cni.cncf.io/networks: ${NETWORKS}
ANNOTATIONS
cat << HEREDOC2 >> ./${NAME}.yaml
  namespace: ${NETOP_APP_NAMESPACE}
spec:
  containers:
  - name: appcntr1
    #image: mellanox/rping-test
    image: harbor.runailabs-ps.com/netop/rdmadbg_cuda_x86_64:latest
    #image: harbor.runailabs-ps.com/netop/rdmadbg_cuda_aarch64:latest
    imagePullPolicy: IfNotPresent
    env:
       - name: SYSCTL_CONFIG
         value: "${SYSCTL_CONFIG}"
    securityContext:
      privileged: true
      capabilities:
        add: ["IPC_LOCK"]
    resources:
HEREDOC2
# Only emit requests:/limits: when something will live under them.
# - GPU lines are present iff NUM_GPUS > 0 (set_gpus already guards on that).
# - Network device-plugin resources are present iff USECASE != sriovnet_dra.
HAS_GPU=false
HAS_NETRES=false
if [ "${NUM_GPUS}" != "" ] && [ "${NUM_GPUS}" -gt 0 ]; then
  HAS_GPU=true
fi
case ${USECASE} in
sriovnet_dra) ;;
*) HAS_NETRES=true ;;
esac
if [ "${HAS_GPU}" = "true" ] || [ "${HAS_NETRES}" = "true" ]; then
cat <<RESHDR >> ./${NAME}.yaml
      requests:
RESHDR
  set_gpus >> ./${NAME}.yaml
  [ "${HAS_NETRES}" = "true" ] && set_network_resource >> ./${NAME}.yaml
cat <<RESHDR2 >> ./${NAME}.yaml
      limits:
RESHDR2
  set_gpus >> ./${NAME}.yaml
  [ "${HAS_NETRES}" = "true" ] && set_network_resource >> ./${NAME}.yaml
fi
case ${USECASE} in
sriovnet_dra)
  set_container_claims >> ./${NAME}.yaml
  ;;
esac
cat << HEREDOC5 >> ./${NAME}.yaml
    command:
    - sh
    - -c
    - sleep inf
HEREDOC5
case ${USECASE} in
sriovnet_dra)
  set_pod_resource_claims >> ./${NAME}.yaml
  ;;
esac
if [ "${NODE}" != "" ];then
cat << NODEDOC >> ./${NAME}.yaml
  nodeSelector:
    # Note: Replace hostname or remove selector altogether
    kubernetes.io/hostname: ${NODE}
NODEDOC
fi
done
