#!/bin/bash
#
# install the network operator.
#
source ${NETOP_ROOT_DIR}/global_ops.cfg
${NETOP_ROOT_DIR}/ops/mk-values.sh
${NETOP_ROOT_DIR}/ops/mk-nic-cluster-policy.sh
if [ "${NIC_CONFIG_ENABLE}" = "true" ];then
  ${NETOP_ROOT_DIR}/ops/mk-nic-config.sh
else
  for DEVICE_TYPE in ${DEVICE_TYPES[@]};do
    rm -f "nic-config-crd-${DEVICE_TYPE}.yaml"
  done
fi
NETOP_NICNODE_FILES=()
if [ ${#NETOP_NODEPOOLS[@]} -gt 0 ]; then
  _IPPOOLS_DONE=false
  _NODEPOOL_LABEL_FILE="${NETOP_NODEPOOL_LABEL_FILE:-node-pool-labels.sh}"
  _NODEPOOL_LABEL_KEY="${NETOP_NODEPOOL_LABEL_KEY:-netop.nvidia.com/pool}"
  _NODEPOOL_LABELS_REQUIRED=false
  for NETLIST_VAR in "${NETOP_NODEPOOLS[@]}"; do
    _SUFFIX="${NETLIST_VAR#NETOP_NETLIST}"
    POOL_ID="${_SUFFIX#_}"
    POOL_LABEL_VALUE="${POOL_ID,,}"
    _POOL_SELECTOR_VAR="NETOP_NODESELECTOR_${POOL_ID}"
    if [ ${#NETOP_NODEPOOLS[@]} -gt 1 ] && [ -z "${!_POOL_SELECTOR_VAR:-}" ]; then
      if [ "${_NODEPOOL_LABELS_REQUIRED}" = "false" ]; then
        {
          echo "#!/bin/bash"
          echo "# Generated by mk-config.sh. Apply these labels before applying multi-pool policies."
        } > "${_NODEPOOL_LABEL_FILE}"
        _NODEPOOL_LABELS_REQUIRED=true
      fi
      export "NETOP_NODESELECTOR_${POOL_ID}=${_NODEPOOL_LABEL_KEY}"
      export "NETOP_NODESELECTOR_VAL_${POOL_ID}=${POOL_LABEL_VALUE}"
      {
        echo ""
        echo "# Pool ${POOL_ID}: label the nodes that should use ${NETLIST_VAR}."
        echo "# ${K8CL} label node <node-name> ${_NODEPOOL_LABEL_KEY}=${POOL_LABEL_VALUE} --overwrite"
      } >> "${_NODEPOOL_LABEL_FILE}"
    fi
    export NETOP_ACTIVE_POOL="${POOL_ID}"
    export NIC_NODE_POLICY_FILE="nic-node-policy${POOL_ID:+-${POOL_ID}}.yaml"
    export NETOP_SRIOV_NODE_POOL_FILE="sriov-node-pool-config${POOL_ID:+-${POOL_ID}}.yaml"
    case ${NETOP_VERSION} in
      26.4.*)
        ${NETOP_ROOT_DIR}/ops/mk-nic-node-policy.sh
        NETOP_NICNODE_FILES+=("${NIC_NODE_POLICY_FILE}")
        ;;
    esac
    # Network CRs and IPPools are shared by resource/network name across
    # node pools. Only the per-pool node policies vary by device list.
    if [ "${_IPPOOLS_DONE}" = "true" ]; then
      export NETOP_SKIP_IPPOOL=true
    else
      unset NETOP_SKIP_IPPOOL
      _IPPOOLS_DONE=true
    fi
    ${NETOP_ROOT_DIR}/ops/mk-network-cr.sh
    ${NETOP_ROOT_DIR}/ops/mk-sriov-node-pool.sh
  done
  if [ "${_NODEPOOL_LABELS_REQUIRED}" = "true" ]; then
    chmod +x "${_NODEPOOL_LABEL_FILE}"
  else
    rm -f "${_NODEPOOL_LABEL_FILE}"
  fi
  unset NETOP_ACTIVE_POOL NIC_NODE_POLICY_FILE NETOP_SRIOV_NODE_POOL_FILE NETOP_SKIP_IPPOOL
else
  ${NETOP_ROOT_DIR}/ops/mk-network-cr.sh
  ${NETOP_ROOT_DIR}/ops/mk-sriov-node-pool.sh
  case ${NETOP_VERSION} in
    26.4.*)
      if [ "${NIC_NODE_POLICY_ENABLE}" = "true" ];then
        ${NETOP_ROOT_DIR}/ops/mk-nic-node-policy.sh
        NETOP_NICNODE_FILES+=("${NIC_NODE_POLICY_FILE}")
      else
        rm -f "${NIC_NODE_POLICY_FILE}"
      fi
      ;;
    *)
      rm -f "${NIC_NODE_POLICY_FILE}"
      ;;
  esac
fi
if [ ${#NETOP_NICNODE_FILES[@]} -gt 0 ]; then
  echo "${NETOP_NICNODE_FILES[@]}" > netop_nicnode_files
else
  rm -f netop_nicnode_files
fi
if [ "${DRA_ENABLE}" = "true" ]; then
  case ${NETOP_VERSION} in
    26.4.*)
      ${NETOP_ROOT_DIR}/ops/mk-dra-cr.sh
      ;;
  esac
else
  rm -f netop_dra_files
fi
